import { useEffect, useRef } from "react";
import { formatHours, formatNum, formatRub, rankFor } from "@/game/model";
import type { Fanfare } from "@/game/store";
import { Button } from "@/components/tok/ui";

export function FanfareModal({ fanfare, onClose }: { fanfare: Fanfare; onClose: () => void }) {
  const leveled = fanfare.levels.length > 0;
  const top = fanfare.levels[fanfare.levels.length - 1];
  useEffect(() => { const onKey=(e:KeyboardEvent)=>{if(e.key==="Escape")onClose()}; document.addEventListener("keydown",onKey); return()=>document.removeEventListener("keydown",onKey)},[onClose]);
  return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"><button type="button" className="scrim absolute inset-0" aria-label="Закрыть" onClick={onClose}/><div className="pop-in relative z-10 w-full max-w-md overflow-hidden rounded-t-3xl bg-surface px-4 pt-4 pb-6 sm:rounded-3xl"><Confetti/><p className="text-sm font-semibold text-primary">{leveled?"Новый уровень":"Смена в копилку"}</p><h2 className="mt-1 font-display text-4xl leading-none">{leveled&&top?`Уровень ${top}`:`+${formatNum(fanfare.xp)} XP`}</h2>{leveled&&top?<p className="mt-2 text-lg">{rankFor(top).name}</p>:null}<div className="mt-4 grid grid-cols-2 gap-2"><Stat label="Опыт" value={`+${formatNum(fanfare.xp)}`}/><Stat label="Монеты" value={`+${formatNum(fanfare.coins)}`}/></div>{fanfare.earned>0||fanfare.orders>0?<div className="mt-3 rounded-3xl bg-primary-container p-4 text-on-primary-container"><div className="font-display text-3xl">{formatRub(fanfare.earned)}</div><p className="mt-1 text-sm">{formatNum(fanfare.orders)} зак. · {formatHours(fanfare.hours)}{fanfare.rate!=null?` · ${formatRub(fanfare.rate)}/ч`:""}</p>{fanfare.scoreWord?<p className="mt-2 text-sm font-semibold">Оценка смены {fanfare.score} · {fanfare.scoreWord}</p>:null}{fanfare.verdict?<p className="mt-1 text-sm opacity-80">{fanfare.verdict}</p>:null}</div>:fanfare.verdict?<p className="mt-3 text-sm text-muted">{fanfare.verdict}</p>:null}{fanfare.records.length>0?<ul className="mt-3 flex flex-col gap-1">{fanfare.records.map(r=><li key={r} className="rounded-full bg-tertiary-container px-3 py-2 text-sm font-semibold text-on-tertiary-container">{r}</li>)}</ul>:null}{fanfare.achievements.length>0?<ul className="mt-3 flex flex-col gap-2">{fanfare.achievements.map(a=><li key={a.id} className="rounded-2xl bg-surface-high px-3 py-2"><div className="text-sm font-semibold">Знак: {a.name}</div><div className="text-xs text-muted">{a.desc}</div></li>)}</ul>:null}<Button className="mt-4 w-full" onClick={onClose}>Дальше</Button></div></div>;
}
function Stat({label,value}:{label:string;value:string}){return <div className="rounded-2xl bg-surface-high px-3 py-3"><div className="text-xs text-muted">{label}</div><div className="font-display text-xl">{value}</div></div>}
function Confetti(){const ref=useRef<HTMLCanvasElement>(null);useEffect(()=>{const canvas=ref.current,parent=canvas?.parentElement;if(!canvas||!parent)return;const ctx=canvas.getContext("2d");if(!ctx)return;const reduce=window.matchMedia("(prefers-reduced-motion: reduce)").matches;if(reduce)return;const dpr=Math.min(2,window.devicePixelRatio||1),w=parent.clientWidth,h=parent.clientHeight;canvas.width=w*dpr;canvas.height=h*dpr;ctx.scale(dpr,dpr);const styles=getComputedStyle(document.documentElement),colors=[styles.getPropertyValue("--md-primary"),styles.getPropertyValue("--md-tertiary"),styles.getPropertyValue("--md-secondary")].map(c=>c.trim());const bits=Array.from({length:42},()=>({x:w*.5+(Math.random()-.5)*40,y:h*.28,vx:(Math.random()-.5)*7,vy:-Math.random()*7-2,s:4+Math.random()*5,c:colors[Math.floor(Math.random()*colors.length)]||"#6ef2a0",r:Math.random()*Math.PI}));let frame=0,raf=0;const loop=()=>{frame++;ctx.clearRect(0,0,w,h);for(const b of bits){b.x+=b.vx;b.y+=b.vy;b.vy+=.12;b.r+=.1;ctx.save();ctx.translate(b.x,b.y);ctx.rotate(b.r);ctx.fillStyle=b.c;ctx.globalAlpha=Math.max(0,1-frame/70);ctx.fillRect(-b.s/2,-b.s/4,b.s,b.s/2);ctx.restore()}if(frame<72)raf=requestAnimationFrame(loop)};raf=requestAnimationFrame(loop);return()=>cancelAnimationFrame(raf)},[]);return <canvas ref={ref} className="pointer-events-none absolute inset-0 h-full w-full"/>}
