import { useState } from "react";
import {
  Award,Banknote,Bike,CalendarDays,Coins,Crown,Flag,Flame,Gauge,Layers,Lock,MapPin,Moon,Package,Route,Star,Sun,Sunrise,Target,Timer,Trophy,Zap,type LucideIcon,
} from "lucide-react";
import { RANKS, SHOP, formatNum, itemOwned, titleName } from "@/game/model";
import { playSound } from "@/game/sound";
import { useGame, useTok } from "@/game/store";
import { Button, Card, Meter } from "@/components/tok/ui";
import { cn } from "@/lib/cn";

const ICONS: Record<string, LucideIcon> = {flag:Flag,calendar:CalendarDays,package:Package,crown:Crown,banknote:Banknote,gauge:Gauge,zap:Zap,timer:Timer,sunrise:Sunrise,moon:Moon,sun:Sun,flame:Flame,coins:Coins,route:Route,star:Star,layers:Layers,target:Target,pin:MapPin,trophy:Trophy,award:Award,bike:Bike};

export function PathView() {
  const game=useGame(),buy=useTok(s=>s.buy),sound=useTok(s=>s.sound),accent=useTok(s=>s.accent),bike=useTok(s=>s.bike),titleId=useTok(s=>s.titleId),setTitle=useTok(s=>s.setTitle),ownedAccents=useTok(s=>s.ownedAccents),ownedBikes=useTok(s=>s.ownedBikes),ownedTitles=useTok(s=>s.ownedTitles);
  const[filter,setFilter]=useState<"all"|"open"|"closed">("all"),[poor,setPoor]=useState<string|null>(null);
  const level=game.level,pct=level.span>0?level.into/level.span:0,openCount=game.achievements.filter(a=>a.unlocked).length,list=game.achievements.filter(a=>filter==="open"?a.unlocked:filter==="closed"?!a.unlocked:true);
  return <div className="flex flex-col gap-4"><div className="rise"><h1 className="font-display text-3xl">Путь</h1><p className="text-sm text-muted">Уровень {level.level} · {game.rank.name}{titleName(titleId)?` · ${titleName(titleId)}`:""}</p></div>
  <Card tone="primary" className="rise rise-1"><div className="flex items-end justify-between gap-3"><div><p className="text-sm font-semibold opacity-80">Опыт</p><p className="font-display text-4xl leading-none">{formatNum(game.xp)}</p></div><p className="text-right text-sm">{formatNum(level.into)} / {formatNum(level.span)}<span className="block opacity-80">до уровня {level.level+1}</span></p></div><div className="xp-track mt-3 h-3 overflow-hidden rounded-full"><div className="h-full rounded-full bg-on-primary-container" style={{width:`${Math.round(pct*100)}%`}}/></div><p className="mt-3 text-sm">{game.rank.blurb}</p>{game.nextRank?<p className="mt-1 text-sm opacity-80">Дальше «{game.nextRank.name}» с уровня {game.nextRank.level}. Ещё {game.nextRank.level-level.level}.</p>:<p className="mt-1 text-sm opacity-80">Дальше рангов нет. Остаётся только город.</p>}</Card>
  <details className="rounded-3xl bg-surface-high px-4 py-3 text-sm"><summary className="cursor-pointer font-semibold">Как качается XP и монеты</summary><p className="mt-2 text-muted">За смену: 14 XP за заказ, 1 XP за каждые 25 ₽, 8 XP за час, чаевые сверху. Серия дней множит это до +63% на 21-й день подряд. Значки и квесты добавляют пачкой. Монеты — примерно 1 за 140 ₽ плюс заказы. Они тратятся только на цвет, вел и титул.</p></details>
  <section className="flex flex-col gap-2"><h2 className="font-semibold">Ранги</h2>{RANKS.map(rank=>{const reached=level.level>=rank.level,current=game.rank.level===rank.level;return <div key={rank.level} className={cn("rounded-3xl px-4 py-3",current?"bg-primary-container text-on-primary-container":"bg-surface-high")}><div className="flex items-center justify-between gap-3"><span className="font-semibold">{rank.name}</span><span className={cn("text-xs font-semibold",!current&&"text-muted")}>ур. {rank.level}</span></div><p className={cn("mt-1 text-sm",current?"opacity-80":"text-muted")}>{reached?rank.blurb:"Ещё закрыт"}</p></div>})}</section>
  <section className="flex flex-col gap-3"><h2 className="font-semibold">Значки {openCount}/{game.achievements.length}</h2><div className="flex gap-2">{([["all","Все"],["open","Открытые"],["closed","Закрытые"]] as const).map(([id,label])=><button key={id} type="button" onClick={()=>setFilter(id)} className={cn("tap min-h-11 rounded-full px-4 text-sm font-semibold",filter===id?"bg-secondary-container text-on-secondary-container":"bg-surface-high text-muted")} aria-pressed={filter===id}>{label}</button>)}</div>
  <div className="grid grid-cols-1 gap-2 sm:grid-cols-2">{list.map(a=>{const Icon=ICONS[a.def.icon]??Award,hidden=a.def.secret&&!a.unlocked;return <Card key={a.def.id} className={cn(!a.unlocked&&"opacity-80")}><div className="flex items-start gap-3"><span className={cn("grid h-11 w-11 shrink-0 place-items-center rounded-2xl",a.unlocked?"bg-primary text-on-primary":"bg-surface-highest text-muted")}>{a.unlocked?<Icon className="h-5 w-5"/>:<Lock className="h-5 w-5"/>}</span><div className="min-w-0 flex-1"><h3 className="font-semibold">{hidden?"Скрытый знак":a.def.name}</h3><p className="text-xs text-muted">{hidden?"Откроется сам, когда случится.":a.def.desc}</p>{a.progress&&!a.unlocked?<div className="mt-2"><Meter value={a.progress.value} max={a.progress.max}/><p className="mt-1 text-xs text-muted">{formatNum(Math.min(a.progress.value,a.progress.max))} / {formatNum(a.progress.max)}</p></div>:<p className="mt-1 text-xs text-primary">+{a.def.xp} XP · +{a.def.coins} монет</p>}</div></div></Card>})}</div></section>
  <section className="flex flex-col gap-3"><div><h2 className="font-semibold">Мастерская</h2><p className="text-sm text-muted">Баланс {formatNum(game.coins)} монет. Внешний вид, не статы.</p></div>{(["accent","bike","title"] as const).map(kind=><div key={kind} className="flex flex-col gap-2"><h3 className="text-sm font-semibold text-muted">{kind==="accent"?"Палитра":kind==="bike"?"Вел":"Титулы"}</h3>{SHOP.filter(item=>item.kind===kind).map(item=>{const owned=itemOwned(item,ownedAccents,ownedBikes,ownedTitles),active=(item.kind==="accent"&&accent===item.ref)||(item.kind==="bike"&&bike===item.ref)||(item.kind==="title"&&titleId===item.ref),can=owned||game.coins>=item.cost;return <div key={item.id} className={cn("flex items-center gap-3 rounded-3xl bg-surface-high px-3 py-3",poor===item.id&&"ring-2 ring-danger")}><div className="min-w-0 flex-1"><div className="font-semibold">{item.name}</div><div className="text-xs text-muted">{item.hint}</div></div><Button variant={active?"tonal":can?"filled":"outline"} onClick={()=>{const res=buy(item.id);if(res==="poor"){setPoor(item.id);return}setPoor(null);playSound(owned?"tap":"coin",sound)}}>{active?"На тебе":owned?"Надеть":can?String(item.cost):`${item.cost} монет`}</Button></div>})}</div>)}{titleId?<Button variant="text" onClick={()=>setTitle(null)}>Снять титул</Button>:null}</section></div>;
}
