import {useMemo,useState,type ReactNode} from "react";
import {BarChart3,Bike,Coins,Flame,Plus,Route,Trash2,UserRound,X,Zap} from "lucide-react";
import {cn} from "@/lib/cn";

type Tab="today"|"stats"|"path"|"me";
type Shift={id:string;date:string;hours:number;orders:number;earned:number;km:number;zone:string};
const KEY="tok-apk-v2";
const rub=(n:number)=>Math.round(n).toLocaleString("ru-RU")+" ₽";
const read=():Shift[]=>{try{const x=JSON.parse(localStorage.getItem(KEY)||"{}");return Array.isArray(x.shifts)?x.shifts:[]}catch{return[]}};
const write=(s:Shift[])=>{try{localStorage.setItem(KEY,JSON.stringify({shifts:s}))}catch{}};

const tabs=[{id:"today" as Tab,label:"Смена",icon:Zap},{id:"stats" as Tab,label:"Разбор",icon:BarChart3},{id:"path" as Tab,label:"Путь",icon:Route},{id:"me" as Tab,label:"Ты",icon:UserRound}];

export function AppLite(){
 const[tab,setTab]=useState<Tab>("today"),[shifts,setShifts]=useState<Shift[]>(read),[open,setOpen]=useState(false),[theme,setTheme]=useState("dark"),[name,setName]=useState("Курьер");
 const total=useMemo(()=>({h:shifts.reduce((a,s)=>a+s.hours,0),o:shifts.reduce((a,s)=>a+s.orders,0),e:shifts.reduce((a,s)=>a+s.earned,0),k:shifts.reduce((a,s)=>a+s.km,0)}),[shifts]);
 const level=1+Math.floor(total.e/5000);
 const update=(s:Shift[])=>{setShifts(s);write(s)};
 return <div data-theme={theme} className="min-h-dvh bg-bg text-fg">
  <div className="mx-auto min-h-dvh max-w-5xl lg:grid lg:grid-cols-[250px_1fr]">
   <aside className="hidden border-r border-outline-soft bg-surface-low p-4 lg:block"><Brand/><div className="mt-8 space-y-1">{tabs.map(t=><Nav t={t} active={tab===t.id} click={()=>setTab(t.id)} wide/>)}</div><div className="mt-12 rounded-3xl bg-surface-high p-4"><div className="text-xs text-muted">Уровень</div><div className="font-display text-xl">{level}</div></div></aside>
   <main className="min-w-0 px-4 pb-24 lg:px-7 lg:pb-8">
    <header className="sticky top-0 z-20 bg-bg/95 py-4 backdrop-blur"><div className="flex items-center gap-2"><div className="flex-1 lg:hidden"><Brand small name={name}/></div><h1 className="hidden flex-1 font-display text-3xl lg:block">{tabs.find(t=>t.id===tab)?.label}</h1><span className="inline-flex min-h-11 items-center gap-1 rounded-full bg-surface-high px-3 font-semibold"><Flame className="h-4 w-4 text-tertiary"/>{shifts.length}</span><span className="inline-flex min-h-11 items-center rounded-full bg-tertiary-container px-3 font-semibold text-on-tertiary-container">{rub(total.e)}</span></div></header>
    {tab==="today"&&<Today shifts={shifts} total={total} add={()=>setOpen(true)} del={id=>update(shifts.filter(s=>s.id!==id))}/>}
    {tab==="stats"&&<Stats shifts={shifts} total={total}/>}
    {tab==="path"&&<Path total={total} level={level}/>}
    {tab==="me"&&<Profile name={name} setName={setName} theme={theme} setTheme={setTheme} demo={()=>update(demo())} clear={()=>update([])}/>}
   </main>
  </div>
  <nav className="fixed inset-x-0 bottom-0 z-30 border-t border-outline-soft bg-surface-low lg:hidden"><div className="grid grid-cols-4 pb-2 pt-1">{tabs.map(t=><Nav t={t} active={tab===t.id} click={()=>setTab(t.id)}/>)}</div></nav>
  {open&&<Sheet close={()=>setOpen(false)} submit={s=>{update([{...s,id:crypto.randomUUID()},...shifts]);setOpen(false)}}/>}
 </div>
}

function Brand({small=false,name}:{small?:boolean;name?:string}){return <div className="flex items-center gap-3"><div className={cn("grid place-items-center rounded-2xl bg-primary text-on-primary",small?"h-11 w-11":"h-12 w-12")}><Bike className="h-6 w-6"/></div><div><div className="font-display text-2xl leading-none">ТОК</div><div className="text-xs text-muted">{name||"доход на линии"}</div></div></div>}
function Nav({t,active,click,wide=false}:{t:typeof tabs[number];active:boolean;click:()=>void;wide?:boolean}){const I=t.icon;return <button onClick={click} className={cn("min-h-12 rounded-full text-sm font-semibold",wide?"flex w-full items-center gap-3 px-4":"w-full text-xs",active?"bg-primary-container text-on-primary-container":"text-muted")}><I className="mx-auto h-5 w-5"/>{t.label}</button>}
function Card({children,accent=false}:{children:ReactNode;accent?:boolean}){return <section className={cn("rounded-3xl p-4",accent?"bg-primary-container text-on-primary-container":"bg-surface-high")}>{children}</section>}
function Today({shifts,total,add,del}:{shifts:Shift[];total:{h:number;o:number;e:number;k:number};add:()=>void;del:(id:string)=>void}){return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-2"><Card accent><div className="text-sm opacity-80">Заработано</div><div className="mt-1 font-display text-4xl">{rub(total.e)}</div><div className="mt-3 text-sm">{total.o} заказов · {total.h} ч</div></Card><Card><div className="text-sm text-muted">Средний темп</div><div className="mt-1 font-display text-4xl">{total.h?rub(total.e/total.h):"0 ₽"}</div><div className="mt-3 text-sm text-muted">за час</div></Card></div><Card><div className="flex items-center justify-between"><div><div className="font-semibold">Добавить смену</div><div className="text-xs text-muted">Запись сохранится на этом устройстве.</div></div><button onClick={add} className="grid h-12 w-12 place-items-center rounded-full bg-primary text-on-primary"><Plus/></button></div></Card><div className="space-y-2">{shifts.slice(0,8).map(s=><div key={s.id} className="rounded-2xl bg-surface-high p-4"><div className="flex items-center justify-between"><div><div className="font-semibold">{s.date} · {s.orders} зак.</div><div className="text-xs text-muted">{s.hours} ч · {s.zone||"без района"}</div></div><div className="flex items-center gap-3"><b>{rub(s.earned)}</b><button onClick={()=>del(s.id)}><Trash2 className="h-5 w-5 text-muted"/></button></div></div></div>)}</div></div>}
function Stats({shifts,total}:{shifts:Shift[];total:{h:number;o:number;e:number;k:number}}){const max=Math.max(1,...shifts.map(s=>s.earned));return <div className="space-y-4"><div className="grid gap-3 sm:grid-cols-3"><Card><small>Доход</small><div className="font-display text-2xl">{rub(total.e)}</div></Card><Card><small>Заказы</small><div className="font-display text-2xl">{total.o}</div></Card><Card><small>Км</small><div className="font-display text-2xl">{total.k}</div></Card></div><Card><h2 className="font-display text-xl">Динамика</h2><div className="mt-4 space-y-3">{shifts.slice().reverse().slice(-10).map(s=><div key={s.id}><div className="mb-1 flex justify-between text-xs text-muted"><span>{s.date}</span><span>{rub(s.earned)}</span></div><div className="h-3 rounded-full bg-surface-low"><div className="h-full rounded-full bg-primary" style={{width:Math.max(5,s.earned/max*100)+"%"}}/></div></div>)}</div></Card></div>}
function Path({total,level}:{total:{h:number;o:number;e:number;k:number};level:number}){const g=[["Первая смена",total.h>0],["100 заказов",total.o>=100],["10 000 ₽",total.e>=10000],["50 часов",total.h>=50]];return <div className="space-y-3"><Card accent><div className="text-sm opacity-80">Уровень</div><div className="font-display text-4xl">{level}</div></Card>{g.map(x=><Card><div className="flex items-center gap-3"><Coins className="text-tertiary"/><div><div className="font-semibold">{x[0]}</div><div className="text-xs text-muted">{x[1]?"Выполнено":"Впереди"}</div></div></div></Card>)}</div>}
function Profile({name,setName,theme,setTheme,demo,clear}:{name:string;setName:(v:string)=>void;theme:string;setTheme:(v:string)=>void;demo:()=>void;clear:()=>void}){return <div className="space-y-4"><Card><div className="flex items-center gap-3"><UserRound/><div><div className="font-display text-2xl">Ты</div><div className="text-sm text-muted">Настройки</div></div></div><label className="mt-4 block text-sm font-semibold">Имя<input className={field} value={name} onChange={e=>setName(e.target.value)}/></label></Card><Card><div className="font-semibold">Тема</div><div className="mt-3 flex gap-2"><button className={button} onClick={()=>setTheme("dark")}>Ночь</button><button className={button} onClick={()=>setTheme("light")}>День</button></div></Card><Card><div className="font-semibold">Данные</div><div className="mt-3 flex gap-2"><button className={button} onClick={demo}>Демо</button><button className={cn(button,"text-danger")} onClick={clear}>Стереть</button></div></Card></div>}
function Sheet({close,submit}:{close:()=>void;submit:(s:Omit<Shift,"id">)=>void}){const[h,setH]=useState("6"),[o,setO]=useState("20"),[e,setE]=useState("2000"),[k,setK]=useState("30"),[z,setZ]=useState("Центр");return <div className="fixed inset-0 z-50 flex items-end justify-center sm:items-center"><button className="scrim absolute inset-0" onClick={close}/><div className="relative z-10 w-full max-w-lg rounded-t-3xl bg-surface p-4 sm:rounded-3xl"><div className="mb-4 flex items-center justify-between"><h2 className="font-display text-xl">Новая смена</h2><button onClick={close}><X/></button></div><div className="grid gap-3 sm:grid-cols-2"><label className="text-sm font-semibold">Часы<input className={field} value={h} onChange={e=>setH(e.target.value)}/></label><label className="text-sm font-semibold">Заказы<input className={field} value={o} onChange={e=>setO(e.target.value)}/></label><label className="text-sm font-semibold">Сумма<input className={field} value={e} onChange={x=>setE(x.target.value)}/></label><label className="text-sm font-semibold">Км<input className={field} value={k} onChange={x=>setK(x.target.value)}/></label><label className="text-sm font-semibold sm:col-span-2">Район<input className={field} value={z} onChange={x=>setZ(x.target.value)}/></label></div><button className={cn(button,"mt-4 w-full bg-primary text-on-primary")} onClick={()=>submit({date:today(),hours:+h||0,orders:Math.round(+o||0),earned:+e||0,km:+k||0,zone:z})}>Сохранить</button></div></div>}
function today(){return new Date().toISOString().slice(0,10)}
function demo():Shift[]{return Array.from({length:7},(_,i)=>({id:crypto.randomUUID(),date:new Date(Date.now()-i*86400000).toISOString().slice(0,10),hours:6,orders:20+i,earned:1800+i*150,km:35+i*2,zone:["Центр","Север","Вокзал"][i%3]}))}
const field="mt-1 min-h-12 w-full rounded-2xl border border-outline-soft bg-surface-low px-3 text-base text-fg outline-none",button="min-h-11 rounded-2xl bg-surface-low px-4 text-sm font-semibold";
